# Generated by Django 5.1.3 on 2024-11-08 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adam',
            old_name='address',
            new_name='actuation_port',
        ),
        migrations.RemoveField(
            model_name='adam',
            name='port',
        ),
    ]
