# Generated by Django 5.1.3 on 2024-11-08 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0002_rename_address_adam_actuation_port_remove_adam_port'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adam',
            unique_together={('ip', 'actuation_port')},
        ),
    ]
