# Generated by Django 5.1.3 on 2024-11-08 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0003_alter_adam_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdamLinkedwith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('other', models.CharField(blank=True, max_length=255, null=True)),
                ('adam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adam', to='gadgets.adam')),
            ],
            options={
                'db_table': 'tbl_adam_linked_with',
            },
        ),
    ]
