# Generated by Django 5.1.3 on 2024-11-09 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0004_adamlinkedwith'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adamlinkedwith',
            unique_together={('client_ip', 'adam')},
        ),
    ]
