# Generated by Django 5.1.3 on 2024-11-14 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0005_alter_adamlinkedwith_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adamlinkedwith',
            name='adam',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adam', to='gadgets.adam'),
        ),
        migrations.AlterField(
            model_name='adamlinkedwith',
            name='client_ip',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
