# Generated by Django 5.1.3 on 2024-11-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Employee', 'Employee'), ('Guard', 'Guard')], default='Employee', max_length=255),
        ),
    ]
