# Generated by Django 5.1.3 on 2024-11-06 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('visitor_type', models.CharField(choices=[('civilian', 'Civilian')], default='civilian', max_length=255)),
                ('address', models.TextField(blank=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('gov_id_type', models.CharField(choices=[('aadhar_card', 'Aadhar_Card')], default='aadhar_card', max_length=50)),
                ('gov_id_no', models.CharField(max_length=255, unique=True)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('is_pass_created', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('other', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_visitors', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_visitors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_visitor',
            },
        ),
    ]
