# Generated by Django 5.1.3 on 2024-11-11 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_visitorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorFaceFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.BinaryField()),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitor_face_feature', to='visitor.visitor')),
            ],
            options={
                'db_table': 'tbl_visitor_face_features',
            },
        ),
    ]
