# Generated by Django 5.1.3 on 2024-11-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorpass',
            name='pass_number',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
