# Generated by Django 5.1.3 on 2024-11-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0003_alter_visitorpass_pass_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorpass',
            name='pass_number',
            field=models.IntegerField(unique=True),
        ),
    ]
